name: Lint Helm charts

on:
  push:
    paths:
      - "charts/**"

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  HELM_VERSION: 3.17.0

jobs:
  lint-helm-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: mamezou-tech/setup-helmfile@v2.1.0
        with:
          helm-version: "v${{ env.HELM_VERSION }}"

      - name: Lint Helm Charts
        run: |
          helm lint charts/*
        working-directory: ${{ github.workspace }}
